trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
   name: selfwindowsagent
   demands: 
    - agent.name -equals SREE-PC

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhubconnection'
        repository: 'srikanthpoosal/devopsrepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'