# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: selfwindowsagent
  demands:
   - agent.name -equals SREE-PC
stages:
 - stage: Build
   displayName: Build image
   jobs:
     - job: Build
       displayName: Build
       pool:
        vmImage: 'ubuntu-latest'
       steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhubconnection'
            repository: 'srikanthpoosal/devopsrepo'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'