name: first-action-workflow
on: workflow_dispatch
jobs:
  build-job:
   runs-on: ubuntu-latest
   steps:
     - name: display greeting
       run: |
            echo "first run"
            echo "second run"
            echo "third run"
     - name: display echo run
       run: echo "this is the last run of pipeline"
  
