name: react_ci_test
on: [push, workflow_dispatch]

jobs:
  test:
   runs-on: ${{ vars.RUNNER }}
   steps:
      - name: get code
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: get cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}    
      - name: Install Dependencies
        run: npm install
      - name: run unit test
        run: npm test -- --watchAll=false
        env:
         CI: true
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: get cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}     
      - name: install dependencies
        run: npm install
      - name: build react
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: buildfiles
          path: build
            
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name:  get build artifacts
          uses: actions/download-artifact@v4
          with: 
            name: buildfiles
        - name: output content
          run: ls    
        - name:  deployapp
          run: echo "deploying.."  
